package net.shadowmage.ancientwarfare;

/**
 * Static replacement for the class generated by the 1.12 build's
 * de.fuerstenau.buildconfig plugin. In that setup UNSTABLE was true for any
 * local build (no GITHUB_REF) and gated extra debug diagnostics only.
 */
public final class BuildConfig {
    public static final String NAME = "ancientwarfare";
    public static final String VERSION = "1.0.0";
    public static final boolean UNSTABLE = true;

    private BuildConfig() {
    }
}
