package net.shadowmage.ancientwarfare.vehicle.model;

import net.minecraft.world.entity.Entity;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.shadowmage.ancientwarfare.core.client.model.LegacyModelBase;
import net.shadowmage.ancientwarfare.core.client.model.LegacyModelRenderer;
import net.shadowmage.ancientwarfare.core.util.Trig;

@OnlyIn(Dist.CLIENT)
public class ModelCatapultStandTurret extends LegacyModelBase {

    LegacyModelRenderer standBaseMidBeam;
    LegacyModelRenderer standLeftBeam;
    LegacyModelRenderer standRightBeam;
    LegacyModelRenderer standFrontBeam;
    LegacyModelRenderer standRearBeam;
    LegacyModelRenderer standTopMidBeam;
    LegacyModelRenderer standTopLeftBeam;
    LegacyModelRenderer standTopRightBeam;
    LegacyModelRenderer standTopFrontBeam;
    LegacyModelRenderer standTopRearBeam;
    LegacyModelRenderer standFlAngle;
    LegacyModelRenderer standFrAngle;
    LegacyModelRenderer standRrAngle;
    LegacyModelRenderer standRlAngle;
    LegacyModelRenderer standLBrace;
    LegacyModelRenderer standRBrace;
    LegacyModelRenderer turretMidBeam;
    LegacyModelRenderer upright1;
    LegacyModelRenderer upright2;
    LegacyModelRenderer turretTopHorizontal;
    LegacyModelRenderer turretLeftAngled;
    LegacyModelRenderer turretRightAngled;
    LegacyModelRenderer pulleyAxle;
    LegacyModelRenderer pulleyArm1;
    LegacyModelRenderer pulleyArm2;
    LegacyModelRenderer turretFrontBeam;
    LegacyModelRenderer turretRearBeam;
    LegacyModelRenderer armMain;
    LegacyModelRenderer bucket1;
    LegacyModelRenderer bucket3;
    LegacyModelRenderer bucket6;
    LegacyModelRenderer bucket4;
    LegacyModelRenderer bucket2;
    LegacyModelRenderer turretLeftBeam1;
    LegacyModelRenderer turretLeftBeam2;
    LegacyModelRenderer turretRightBeam1;
    LegacyModelRenderer turretRightBeam2;
    LegacyModelRenderer turretLeftAngle2;
    LegacyModelRenderer turretRightAngle2;

    public ModelCatapultStandTurret() {
        standBaseMidBeam = new LegacyModelRenderer(this, "standBaseMidBeam");
        standBaseMidBeam.setTextureOffset(0, 0);
        standBaseMidBeam.setTextureSize(256, 256);
        standBaseMidBeam.setRotationPoint(0.0f, 0.0f, 0.0f);
        setPieceRotation(standBaseMidBeam, 0.0f, 0.0f, 0.0f);
        standBaseMidBeam.addBox(-18.0f, -2.0f, -1.5f, 36, 2, 3);
        standLeftBeam = new LegacyModelRenderer(this, "standLeftBeam");
        standLeftBeam.setTextureOffset(0, 63);
        standLeftBeam.setTextureSize(256, 256);
        standLeftBeam.setRotationPoint(19.0f, 0.0f, 0.0f);
        setPieceRotation(standLeftBeam, 0.0f, 0.0f, 0.0f);
        standLeftBeam.addBox(-1.0f, -2.0f, -19.5f, 3, 2, 39);
        standBaseMidBeam.addChild(standLeftBeam);
        standRightBeam = new LegacyModelRenderer(this, "standRightBeam");
        standRightBeam.setTextureOffset(0, 63);
        standRightBeam.setTextureSize(256, 256);
        standRightBeam.setRotationPoint(-20.0f, 0.0f, 0.0f);
        setPieceRotation(standRightBeam, 0.0f, 0.0f, 0.0f);
        standRightBeam.addBox(-1.0f, -2.0f, -19.5f, 3, 2, 39);
        standBaseMidBeam.addChild(standRightBeam);
        standFrontBeam = new LegacyModelRenderer(this, "standFrontBeam");
        standFrontBeam.setTextureOffset(0, 6);
        standFrontBeam.setTextureSize(256, 256);
        standFrontBeam.setRotationPoint(0.0f, 0.0f, -22.5f);
        setPieceRotation(standFrontBeam, 0.0f, 0.0f, 0.0f);
        standFrontBeam.addBox(-21.0f, -2.0f, -1.0f, 42, 2, 4);
        standBaseMidBeam.addChild(standFrontBeam);
        standRearBeam = new LegacyModelRenderer(this, "standRearBeam");
        standRearBeam.setTextureOffset(0, 6);
        standRearBeam.setTextureSize(256, 256);
        standRearBeam.setRotationPoint(0.0f, 0.0f, 19.5f);
        setPieceRotation(standRearBeam, 0.0f, 0.0f, 0.0f);
        standRearBeam.addBox(-21.0f, -2.0f, 0.0f, 42, 2, 4);
        standBaseMidBeam.addChild(standRearBeam);
        standTopMidBeam = new LegacyModelRenderer(this, "standTopMidBeam");
        standTopMidBeam.setTextureOffset(0, 13);
        standTopMidBeam.setTextureSize(256, 256);
        standTopMidBeam.setRotationPoint(0.0f, -7.5f, 0.0f);
        setPieceRotation(standTopMidBeam, 0.0f, 0.0f, 0.0f);
        standTopMidBeam.addBox(-16.0f, -1.0f, -1.5f, 32, 2, 3);
        standBaseMidBeam.addChild(standTopMidBeam);
        standTopLeftBeam = new LegacyModelRenderer(this, "standTopLeftBeam");
        standTopLeftBeam.setTextureOffset(0, 25);
        standTopLeftBeam.setTextureSize(256, 256);
        standTopLeftBeam.setRotationPoint(16.0f, -7.5f, 0.0f);
        setPieceRotation(standTopLeftBeam, 0.0f, 0.0f, 0.0f);
        standTopLeftBeam.addBox(0.0f, -1.0f, -17.5f, 3, 2, 35);
        standBaseMidBeam.addChild(standTopLeftBeam);
        standTopRightBeam = new LegacyModelRenderer(this, "standTopRightBeam");
        standTopRightBeam.setTextureOffset(0, 25);
        standTopRightBeam.setTextureSize(256, 256);
        standTopRightBeam.setRotationPoint(-19.0f, -7.5f, 0.0f);
        setPieceRotation(standTopRightBeam, 0.0f, 0.0f, 0.0f);
        standTopRightBeam.addBox(0.0f, -1.0f, -17.5f, 3, 2, 35);
        standBaseMidBeam.addChild(standTopRightBeam);
        standTopFrontBeam = new LegacyModelRenderer(this, "standTopFrontBeam");
        standTopFrontBeam.setTextureOffset(0, 19);
        standTopFrontBeam.setTextureSize(256, 256);
        standTopFrontBeam.setRotationPoint(0.0f, -7.5f, -20.5f);
        setPieceRotation(standTopFrontBeam, 0.0f, 0.0f, 0.0f);
        standTopFrontBeam.addBox(-19.0f, -1.0f, 0.0f, 38, 2, 3);
        standBaseMidBeam.addChild(standTopFrontBeam);
        standTopRearBeam = new LegacyModelRenderer(this, "standTopRearBeam");
        standTopRearBeam.setTextureOffset(0, 19);
        standTopRearBeam.setTextureSize(256, 256);
        standTopRearBeam.setRotationPoint(0.0f, -7.5f, 17.5f);
        setPieceRotation(standTopRearBeam, 0.0f, 0.0f, 0.0f);
        standTopRearBeam.addBox(-19.0f, -1.0f, 0.0f, 38, 2, 3);
        standBaseMidBeam.addChild(standTopRearBeam);
        standFlAngle = new LegacyModelRenderer(this, "standFlAngle");
        standFlAngle.setTextureOffset(0, 105);
        standFlAngle.setTextureSize(256, 256);
        standFlAngle.setRotationPoint(18.5f, -8.5f, -20.0f);
        setPieceRotation(standFlAngle, -0.26179937f, 0.0f, -0.26179928f);
        standFlAngle.addBox(-2.0f, 0.0f, 0.0f, 2, 7, 2);
        standBaseMidBeam.addChild(standFlAngle);
        standFrAngle = new LegacyModelRenderer(this, "standFrAngle");
        standFrAngle.setTextureOffset(0, 105);
        standFrAngle.setTextureSize(256, 256);
        standFrAngle.setRotationPoint(-18.5f, -8.5f, -20.0f);
        setPieceRotation(standFrAngle, -0.26179934f, 0.0f, 0.26179928f);
        standFrAngle.addBox(0.0f, 0.0f, 0.0f, 2, 7, 2);
        standBaseMidBeam.addChild(standFrAngle);
        standRrAngle = new LegacyModelRenderer(this, "standRrAngle");
        standRrAngle.setTextureOffset(0, 105);
        standRrAngle.setTextureSize(256, 256);
        standRrAngle.setRotationPoint(-18.5f, -8.5f, 20.0f);
        setPieceRotation(standRrAngle, 0.26179934f, 0.0f, 0.26179928f);
        standRrAngle.addBox(0.0f, 0.0f, -2.0f, 2, 7, 2);
        standBaseMidBeam.addChild(standRrAngle);
        standRlAngle = new LegacyModelRenderer(this, "standRlAngle");
        standRlAngle.setTextureOffset(0, 105);
        standRlAngle.setTextureSize(256, 256);
        standRlAngle.setRotationPoint(18.5f, -8.5f, 20.0f);
        setPieceRotation(standRlAngle, 0.2617993f, 0.0f, -0.26179928f);
        standRlAngle.addBox(-2.0f, 0.0f, -2.0f, 2, 7, 2);
        standBaseMidBeam.addChild(standRlAngle);
        standLBrace = new LegacyModelRenderer(this, "standLBrace");
        standLBrace.setTextureOffset(9, 105);
        standLBrace.setTextureSize(256, 256);
        standLBrace.setRotationPoint(16.0f, -6.5f, -1.0f);
        setPieceRotation(standLBrace, 0.0f, 0.0f, 0.0f);
        standLBrace.addBox(0.0f, 0.0f, 0.0f, 2, 5, 2);
        standBaseMidBeam.addChild(standLBrace);
        standRBrace = new LegacyModelRenderer(this, "standRBrace");
        standRBrace.setTextureOffset(9, 105);
        standRBrace.setTextureSize(256, 256);
        standRBrace.setRotationPoint(-18.0f, -6.5f, -1.0f);
        setPieceRotation(standRBrace, 0.0f, 0.0f, 0.0f);
        standRBrace.addBox(0.0f, 0.0f, 0.0f, 2, 5, 2);
        standBaseMidBeam.addChild(standRBrace);
        turretMidBeam = new LegacyModelRenderer(this, "turretMidBeam");
        turretMidBeam.setTextureOffset(0, 128);
        turretMidBeam.setTextureSize(256, 256);
        turretMidBeam.setRotationPoint(0.0f, -9.5f, 0.0f);
        setPieceRotation(turretMidBeam, 0.0f, 0.0f, 0.0f);
        turretMidBeam.addBox(-12.0f, -1.0f, -1.5f, 24, 2, 3);
        upright1 = new LegacyModelRenderer(this, "upright1");
        upright1.setTextureOffset(9, 150);
        upright1.setTextureSize(256, 256);
        upright1.setRotationPoint(-15.0f, -19.0f, -1.5f);
        setPieceRotation(upright1, 0.0f, 0.0f, 0.0f);
        upright1.addBox(0.0f, 0.0f, 0.0f, 3, 20, 3);
        turretMidBeam.addChild(upright1);
        upright2 = new LegacyModelRenderer(this, "upright2");
        upright2.setTextureOffset(9, 150);
        upright2.setTextureSize(256, 256);
        upright2.setRotationPoint(12.0f, -19.0f, -1.5f);
        setPieceRotation(upright2, 0.0f, 0.0f, 0.0f);
        upright2.addBox(0.0f, 0.0f, 0.0f, 3, 20, 3);
        turretMidBeam.addChild(upright2);
        turretTopHorizontal = new LegacyModelRenderer(this, "turretTopHorizontal");
        turretTopHorizontal.setTextureOffset(0, 140);
        turretTopHorizontal.setTextureSize(256, 256);
        turretTopHorizontal.setRotationPoint(-12.0f, -19.0f, -1.5f);
        setPieceRotation(turretTopHorizontal, 0.0f, 0.0f, 0.0f);
        turretTopHorizontal.addBox(0.0f, 0.0f, 0.0f, 24, 3, 3);
        turretMidBeam.addChild(turretTopHorizontal);
        turretLeftAngled = new LegacyModelRenderer(this, "turretLeftAngled");
        turretLeftAngled.setTextureOffset(0, 150);
        turretLeftAngled.setTextureSize(256, 256);
        turretLeftAngled.setRotationPoint(12.5f, -19.0f, -1.0f);
        setPieceRotation(turretLeftAngled, -0.7853982f, 0.0f, 0.0f);
        turretLeftAngled.addBox(0.0f, 0.0f, 0.0f, 2, 26, 2);
        turretMidBeam.addChild(turretLeftAngled);
        turretRightAngled = new LegacyModelRenderer(this, "turretRightAngled");
        turretRightAngled.setTextureOffset(0, 150);
        turretRightAngled.setTextureSize(256, 256);
        turretRightAngled.setRotationPoint(-14.5f, -19.0f, -1.0f);
        setPieceRotation(turretRightAngled, -0.7853961f, 0.0f, 0.0f);
        turretRightAngled.addBox(0.0f, 0.0f, 0.0f, 2, 26, 2);
        turretMidBeam.addChild(turretRightAngled);
        pulleyAxle = new LegacyModelRenderer(this, "pulleyAxle");
        pulleyAxle.setTextureOffset(0, 147);
        pulleyAxle.setTextureSize(256, 256);
        pulleyAxle.setRotationPoint(2.0f, -3.0f, 0.0f);
        setPieceRotation(pulleyAxle, -4.9455734E-6f, 0.0f, 0.0f);
        pulleyAxle.addBox(-18.0f, -0.5f, -0.5f, 30, 1, 1);
        pulleyArm1 = new LegacyModelRenderer(this, "pulleyArm1");
        pulleyArm1.setTextureOffset(68, 140);
        pulleyArm1.setTextureSize(256, 256);
        pulleyArm1.setRotationPoint(-18.0f, 0.0f, 0.0f);
        setPieceRotation(pulleyArm1, 0.0f, 0.0f, 0.0f);
        pulleyArm1.addBox(-0.5f, -0.5f, -4.5f, 1, 1, 9);
        pulleyArm2 = new LegacyModelRenderer(this, "pulleyArm2");
        pulleyArm2.setTextureOffset(63, 140);
        pulleyArm2.setTextureSize(256, 256);
        pulleyArm2.setRotationPoint(0.0f, 0.0f, 0.0f);
        setPieceRotation(pulleyArm2, 0.0f, 0.0f, 0.0f);
        pulleyArm2.addBox(-0.5f, -4.5f, -0.5f, 1, 9, 1);
        pulleyArm1.addChild(pulleyArm2);
        pulleyAxle.addChild(pulleyArm1);
        turretMidBeam.addChild(pulleyAxle);
        turretFrontBeam = new LegacyModelRenderer(this, "turretFrontBeam");
        turretFrontBeam.setTextureOffset(0, 134);
        turretFrontBeam.setTextureSize(256, 256);
        turretFrontBeam.setRotationPoint(0.0f, 0.0f, -18.0f);
        setPieceRotation(turretFrontBeam, 0.0f, 0.0f, 0.0f);
        turretFrontBeam.addBox(-15.0f, -1.0f, -1.5f, 30, 2, 3);
        turretMidBeam.addChild(turretFrontBeam);
        turretRearBeam = new LegacyModelRenderer(this, "turretRearBeam");
        turretRearBeam.setTextureOffset(0, 134);
        turretRearBeam.setTextureSize(256, 256);
        turretRearBeam.setRotationPoint(0.0f, 0.0f, 18.0f);
        setPieceRotation(turretRearBeam, 0.0f, 0.0f, 0.0f);
        turretRearBeam.addBox(-15.0f, -1.0f, -1.5f, 30, 2, 3);
        turretMidBeam.addChild(turretRearBeam);
        armMain = new LegacyModelRenderer(this, "armMain");
        armMain.setTextureOffset(0, 179);
        armMain.setTextureSize(256, 256);
        armMain.setRotationPoint(0.0f, -3.0f, 0.0f);
        setPieceRotation(armMain, -1.2691628E-7f, 0.0f, 0.0f);
        armMain.addBox(-1.0f, -1.0f, -1.5f, 2, 2, 29);
        bucket1 = new LegacyModelRenderer(this, "bucket1");
        bucket1.setTextureOffset(63, 151);
        bucket1.setTextureSize(256, 256);
        bucket1.setRotationPoint(-4.0f, -1.5f, 27.0f);
        setPieceRotation(bucket1, 0.0f, 0.0f, 0.0f);
        bucket1.addBox(0.0f, 0.0f, 0.0f, 8, 4, 1);
        armMain.addChild(bucket1);
        bucket3 = new LegacyModelRenderer(this, "bucket3");
        bucket3.setTextureOffset(83, 152);
        bucket3.setTextureSize(256, 256);
        bucket3.setRotationPoint(4.0f, -1.5f, 28.0f);
        setPieceRotation(bucket3, 0.0f, 0.0f, 0.0f);
        bucket3.addBox(0.0f, 0.0f, 0.0f, 1, 4, 8);
        armMain.addChild(bucket3);
        bucket6 = new LegacyModelRenderer(this, "bucket6");
        bucket6.setTextureOffset(63, 157);
        bucket6.setTextureSize(256, 256);
        bucket6.setRotationPoint(-4.0f, -1.5f, 36.0f);
        setPieceRotation(bucket6, 0.0f, 0.0f, 0.0f);
        bucket6.addBox(0.0f, 0.0f, 0.0f, 8, 4, 1);
        armMain.addChild(bucket6);
        bucket4 = new LegacyModelRenderer(this, "bucket4");
        bucket4.setTextureOffset(50, 170);
        bucket4.setTextureSize(256, 256);
        bucket4.setRotationPoint(-4.0f, 2.5f, 28.0f);
        setPieceRotation(bucket4, 0.0f, 0.0f, 0.0f);
        bucket4.addBox(0.0f, 0.0f, 0.0f, 8, 1, 8);
        armMain.addChild(bucket4);
        bucket2 = new LegacyModelRenderer(this, "bucket2");
        bucket2.setTextureOffset(83, 165);
        bucket2.setTextureSize(256, 256);
        bucket2.setRotationPoint(-5.0f, -1.5f, 28.0f);
        setPieceRotation(bucket2, 0.0f, 0.0f, 0.0f);
        bucket2.addBox(0.0f, 0.0f, 0.0f, 1, 4, 8);
        armMain.addChild(bucket2);
        turretMidBeam.addChild(armMain);
        turretLeftBeam1 = new LegacyModelRenderer(this, "turretLeftBeam1");
        turretLeftBeam1.setTextureOffset(22, 150);
        turretLeftBeam1.setTextureSize(256, 256);
        turretLeftBeam1.setRotationPoint(12.0f, 0.0f, -16.5f);
        setPieceRotation(turretLeftBeam1, 0.0f, 0.0f, 0.0f);
        turretLeftBeam1.addBox(0.0f, -1.0f, 0.0f, 3, 2, 15);
        turretMidBeam.addChild(turretLeftBeam1);
        turretLeftBeam2 = new LegacyModelRenderer(this, "turretLeftBeam2");
        turretLeftBeam2.setTextureOffset(22, 150);
        turretLeftBeam2.setTextureSize(256, 256);
        turretLeftBeam2.setRotationPoint(12.0f, 0.0f, 1.5f);
        setPieceRotation(turretLeftBeam2, 0.0f, 0.0f, 0.0f);
        turretLeftBeam2.addBox(0.0f, -1.0f, 0.0f, 3, 2, 15);
        turretMidBeam.addChild(turretLeftBeam2);
        turretRightBeam1 = new LegacyModelRenderer(this, "turretRightBeam1");
        turretRightBeam1.setTextureOffset(22, 150);
        turretRightBeam1.setTextureSize(256, 256);
        turretRightBeam1.setRotationPoint(-15.0f, 0.0f, -16.5f);
        setPieceRotation(turretRightBeam1, 0.0f, 0.0f, 0.0f);
        turretRightBeam1.addBox(0.0f, -1.0f, 0.0f, 3, 2, 15);
        turretMidBeam.addChild(turretRightBeam1);
        turretRightBeam2 = new LegacyModelRenderer(this, "turretRightBeam2");
        turretRightBeam2.setTextureOffset(22, 150);
        turretRightBeam2.setTextureSize(256, 256);
        turretRightBeam2.setRotationPoint(-15.0f, 0.0f, 1.5f);
        setPieceRotation(turretRightBeam2, 0.0f, 0.0f, 0.0f);
        turretRightBeam2.addBox(0.0f, -1.0f, 0.0f, 3, 2, 15);
        turretMidBeam.addChild(turretRightBeam2);
        turretLeftAngle2 = new LegacyModelRenderer(this, "turretLeftAngle2");
        turretLeftAngle2.setTextureOffset(0, 150);
        turretLeftAngle2.setTextureSize(256, 256);
        turretLeftAngle2.setRotationPoint(12.5f, -19.0f, 1.0f);
        setPieceRotation(turretLeftAngle2, 0.7853982f, 0.0f, 0.0f);
        turretLeftAngle2.addBox(0.0f, 0.0f, -2.0f, 2, 26, 2);
        turretMidBeam.addChild(turretLeftAngle2);
        turretRightAngle2 = new LegacyModelRenderer(this, "turretRightAngle2");
        turretRightAngle2.setTextureOffset(0, 150);
        turretRightAngle2.setTextureSize(256, 256);
        turretRightAngle2.setRotationPoint(-14.5f, -19.0f, 1.0f);
        setPieceRotation(turretRightAngle2, 0.7853982f, 1.4044014E-7f, 0.0f);
        turretRightAngle2.addBox(0.0f, 0.0f, -2.0f, 2, 26, 2);
        turretMidBeam.addChild(turretRightAngle2);

    }

    @Override
    public void render(Entity entity, float f1, float f2, float f3, float f4, float f5, float f6) {
        super.render(entity, f1, f2, f3, f4, f5, f6);
        setRotationAngles(f1, f2, f3, f4, f5, f6, entity);
        standBaseMidBeam.render(f6);
        turretMidBeam.render(f6);
    }

    public void setPieceRotation(LegacyModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setTurretRotation(float yaw) {
        this.turretMidBeam.rotateAngleY = Trig.toRadians(yaw);
    }

    public void setArmRotation(float pitch) {
        this.armMain.rotateAngleX = Trig.toRadians(pitch);
    }

    public void setCrankRotations(float angle) {
        this.pulleyAxle.rotateAngleX = Trig.toRadians(angle);
    }
}
